### ISSUE TITLE
[Question] Merge `develop` into `master`

### ISSUE THREAD

**Issue by bnn1** [mcmunder/universal-rxjs-ajax#13]
Hey, thanks for the library!  

I tried using universal-rxjs-ajax v2.0.4 with rxjs 7.1.0 but it doesn't play nice - the `request` function typing is wrong.  
I know that working version is in the develop branch but there's no way to import `request` from the `develop` without typescript warnings. 

So.. when the release of develop branch is planned? Maybe you could release beta version if you think develop is not ready to publish?

**Comment by mcmunder** [comment]
Done! Sorry for taking ages!! I was busy with many other things.
