### ISSUE TITLE
packed is making webpack import whole rxjs library

### ISSUE THREAD

**Issue by Tomekmularczyk** [mcmunder/universal-rxjs-ajax#2]
I just checked with webpack-bundle-analyzer that replacing: 

`import { ajax } from 'rxjs/observable/dom/ajax';`

with 

`import { request } from 'universal-rxjs-ajax';`

makes importing whole `rxjs` library :/

**Comment by mcmunder** [comment]
Thanks @Tomekmularczyk! Your PR solved this issue and is now merged in and published!

**Comment by Tomekmularczyk** [comment]
@mcmunder Thanks a lot!
