### ISSUE TITLE
Support for Rxjs v6

### ISSUE THREAD

**Issue by Tomekmularczyk** [mcmunder/universal-rxjs-ajax#8]
I've created PR #7  for a new version that will support Rxjs v6. Can I get this reviewed and possibly merged? I would like to migrate my code to RxJSv6.

**Comment by mcmunder** [comment]
Hey Tomek! Sure, I will look at it. Sorry for the delay, I was very busy... Thanks for the PR!

**Comment by mcmunder** [comment]
btw: I started to use [git-flow](https://jeffkreeftmeijer.com/git-flow/) for the project so I merged your PR into develop... Closing this issue.
